import {BarChartGraphic} from '@core/node/graphic/design/chart/bar.chart.graphic';
import {LineChartGraphic} from '@core/node/graphic/design/chart/line.chart.graphic';
import {PieChartGraphic} from '@core/node/graphic/design/chart/pie.chart.graphic';
import {LinesChartGraphic} from '@core/node/graphic/design/chart/lines.chart.graphic';
import {ImageGraphic} from '@core/node/graphic/design/auxiliary/image.graphic';
import {TextGraphic} from '@core/node/graphic/design/auxiliary/text.graphic';
import {ClockGraphic} from '@core/node/graphic/design/custom/clock.graphic';
import {FlipNumberGraphic} from '@core/node/graphic/design/custom/flip.number.graphic';
import {GaugeChartGraphic} from '@core/node/graphic/design/chart/gauge.chart.graphic';
import {RingChartGraphic} from '@core/node/graphic/design/chart/ring.chart.graphic';
import {WordCloudChartGraphic} from '@core/node/graphic/design/chart/word.cloud.chart.graphic';
import {MapChartGraphic} from '@core/node/graphic/design/chart/map/map.chart.graphic';
import {TableGraphic} from '@core/node/graphic/design/custom/table.graphic';

const map = new Map();
map.set('bar.chart.graphic', BarChartGraphic);
map.set('line.chart.graphic', LineChartGraphic);
map.set('pie.chart.graphic', PieChartGraphic);
map.set('lines.chart.graphic', LinesChartGraphic);
map.set('image.graphic', ImageGraphic);
map.set('text.graphic', TextGraphic);
map.set('clock.graphic', ClockGraphic);
map.set('table.graphic', TableGraphic);
map.set('flip.number.graphic', FlipNumberGraphic);
map.set('gauge.chart.graphic', GaugeChartGraphic);
map.set('ring.chart.graphic', RingChartGraphic);
map.set('map.chart.graphic', MapChartGraphic);
map.set('wordCloud.chart.graphic', WordCloudChartGraphic);
export const graphicMap = map;
