import {BarChartGraphic} from '@core/node/graphic/chart/bar.chart.graphic';
import {LineChartGraphic} from '@core/node/graphic/chart/line.chart.graphic';
import {PieChartGraphic} from '@core/node/graphic/chart/pie.chart.graphic';
import {LinesChartGraphic} from '@core/node/graphic/chart/lines.chart.graphic';
import {ImageGraphic} from '@core/node/graphic/auxiliary/image.graphic';
import {TextGraphic} from '@core/node/graphic/auxiliary/text.graphic';
import {ClockGraphic} from '@core/node/graphic/custom/clock.graphic';
import {FlipNumberGraphic} from '@core/node/graphic/custom/flip.number.graphic';
import {GaugeChartGraphic} from '@core/node/graphic/chart/gauge.chart.graphic';
import {RingChartGraphic} from '@core/node/graphic/chart/ring.chart.graphic';
import {WordCloudChartGraphic} from '@core/node/graphic/chart/word.cloud.chart.graphic';
import {MapChartGraphic} from '@core/node/graphic/chart/map.chart.graphic';
import {TableGraphic} from '@core/node/graphic/custom/table.graphic';
import {BarConfigComponent} from '../../../components/graphic.config/chart/bar.config.component';
import {ImageConfigComponent} from '../../../components/graphic.config/auxiliary/image.config.component';
import {LineConfigComponent} from '../../../components/graphic.config/chart/line.config.component';
import {PieConfigComponent} from '../../../components/graphic.config/chart/pie.config.component';
import {TextConfigComponent} from '../../../components/graphic.config/auxiliary/text.config.component';
import {GaugeConfigComponent} from '../../../components/graphic.config/chart/gauge.config.component';
import {RingConfigComponent} from '../../../components/graphic.config/chart/ring.config.component';
import {MapConfigComponent} from '../../../components/graphic.config/chart/map.config.component';
import {WordCloudConfigComponent} from '../../../components/graphic.config/chart/word.cloud.config.component';

const map = new Map();
map.set('bar.chart.graphic', BarChartGraphic);
map.set('line.chart.graphic', LineChartGraphic);
map.set('pie.chart.graphic', PieChartGraphic);
map.set('lines.chart.graphic', LinesChartGraphic);
map.set('image.graphic', ImageGraphic);
map.set('text.graphic', TextGraphic);
map.set('clock.graphic', ClockGraphic);
map.set('table.graphic', TableGraphic);
map.set('flip.number.graphic', FlipNumberGraphic);
map.set('gauge.chart.graphic', GaugeChartGraphic);
map.set('ring.chart.graphic', RingChartGraphic);
map.set('map.chart.graphic', MapChartGraphic);
map.set('wordCloud.chart.graphic', WordCloudChartGraphic);
export const graphicMap = map;

const map1 = new Map();
map1.set('bar.chart.graphic', BarConfigComponent);
map1.set('line.chart.graphic', LineConfigComponent);
map1.set('pie.chart.graphic', PieConfigComponent);
map1.set('lines.chart.graphic', LineConfigComponent);
map1.set('image.graphic', ImageConfigComponent);
map1.set('text.graphic', TextConfigComponent);
map1.set('clock.graphic', TextConfigComponent);
map1.set('table.graphic', WordCloudConfigComponent);
map1.set('flip.number.graphic', WordCloudConfigComponent);
map1.set('gauge.chart.graphic', GaugeConfigComponent);
map1.set('ring.chart.graphic', RingConfigComponent);
map1.set('map.chart.graphic', MapConfigComponent);
map1.set('wordCloud.chart.graphic', WordCloudConfigComponent);
export const graphicConfigMap = map1;
